apiVersion: apimanagement.cloud/v1alpha1
kind: APIConfig
metadata:
  name: simple-api-config
spec:
  gateway: gateway
  routes:
  - destination:
      address:
        host: service
        port: 8080
    rules:
    - match:
        path: /api/v1/service
      pathRewrite: /
