/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/dmol5e/api-management-app/api-publisher/pkg/apis/apimanagement/v1alpha1"
	scheme "github.com/dmol5e/api-management-app/api-publisher/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// APIConfigsGetter has a method to return a APIConfigInterface.
// A group's client should implement this interface.
type APIConfigsGetter interface {
	APIConfigs(namespace string) APIConfigInterface
}

// APIConfigInterface has methods to work with APIConfig resources.
type APIConfigInterface interface {
	Create(ctx context.Context, aPIConfig *v1alpha1.APIConfig, opts v1.CreateOptions) (*v1alpha1.APIConfig, error)
	Update(ctx context.Context, aPIConfig *v1alpha1.APIConfig, opts v1.UpdateOptions) (*v1alpha1.APIConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.APIConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.APIConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIConfig, err error)
	APIConfigExpansion
}

// aPIConfigs implements APIConfigInterface
type aPIConfigs struct {
	client rest.Interface
	ns     string
}

// newAPIConfigs returns a APIConfigs
func newAPIConfigs(c *ApimanagementV1alpha1Client, namespace string) *aPIConfigs {
	return &aPIConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aPIConfig, and returns the corresponding aPIConfig object, and an error if there is any.
func (c *aPIConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APIConfig, err error) {
	result = &v1alpha1.APIConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apiconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of APIConfigs that match those selectors.
func (c *aPIConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APIConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.APIConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apiconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aPIConfigs.
func (c *aPIConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("apiconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aPIConfig and creates it.  Returns the server's representation of the aPIConfig, and an error, if there is any.
func (c *aPIConfigs) Create(ctx context.Context, aPIConfig *v1alpha1.APIConfig, opts v1.CreateOptions) (result *v1alpha1.APIConfig, err error) {
	result = &v1alpha1.APIConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("apiconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aPIConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aPIConfig and updates it. Returns the server's representation of the aPIConfig, and an error, if there is any.
func (c *aPIConfigs) Update(ctx context.Context, aPIConfig *v1alpha1.APIConfig, opts v1.UpdateOptions) (result *v1alpha1.APIConfig, err error) {
	result = &v1alpha1.APIConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apiconfigs").
		Name(aPIConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aPIConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aPIConfig and deletes it. Returns an error if one occurs.
func (c *aPIConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apiconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aPIConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apiconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aPIConfig.
func (c *aPIConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIConfig, err error) {
	result = &v1alpha1.APIConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("apiconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
