kind: Service
apiVersion: v1
metadata:
  name: 'api-publisher'
spec:
  ports:
    -   name: web
        port: 8080
        targetPort: 8080
    -   name: grpc
        port: 15010
        targetPort: 15010
  selector:
    name: 'api-publisher'