kind: Deployment
apiVersion: apps/v1
metadata:
  name: 'api-publisher'
  labels:
    name: 'api-publisher'
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: 'api-publisher'
    spec:
      containers:
        -   name: 'api-publisher'
            image: dmol5e/api-publisher:latest
            imagePullPolicy: Always
            args:
              - ''
            ports:
              -   name: web
                  containerPort: 8080
                  protocol: TCP
              -   name: grpc
                  containerPort: 15010
                  protocol: TCP
            env:
              -   name: CLOUD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              -   name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              -   name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
            resources:
              requests:
                cpu: '100m'
                memory: '100Mi'
              limits:
                cpu: '100m'
                memory: '100Mi'
            livenessProbe:
              httpGet:
                path: /health
                port: web
              initialDelaySeconds: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                path: /ready
                port: web
              initialDelaySeconds: 5
              timeoutSeconds: 5
  selector:
    matchLabels:
      name: 'api-publisher'
