apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apiconfigs.apimanagement.cloud
spec:
  group: apimanagement.cloud
  names:
    kind: APIConfig
    listKind: APIConfigList
    plural: apiconfigs
    shortNames:
    - apicfg
    singular: apiconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              gateway:
                type: string
              routes:
                items:
                  format: object
                  properties:
                    destination:
                      properties:
                        address:
                          properties:
                            host:
                              type: string
                            port:
                              type: integer
                          type: object
                      type: object
                    rules:
                      items:
                        format: object
                        properties:
                          match:
                            properties:
                              headers:
                                items:
                                  format: object
                                  properties:
                                    name:
                                      type: string
                                    value:
                                      type: string
                                  type: object
                                type: array
                              path:
                                type: string
                            type: object
                          pathRewrite:
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
            required:
            - gateway
            type: object
        type: object
    served: true
    storage: true