/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/dmol5e/api-management-app/api-publisher/pkg/apis/apimanagement/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRouteConfigs implements RouteConfigInterface
type FakeRouteConfigs struct {
	Fake *FakeApimanagementV1alpha1
	ns   string
}

var routeconfigsResource = schema.GroupVersionResource{Group: "apimanagement.cloud", Version: "v1alpha1", Resource: "routeconfigs"}

var routeconfigsKind = schema.GroupVersionKind{Group: "apimanagement.cloud", Version: "v1alpha1", Kind: "RouteConfig"}

// Get takes name of the routeConfig, and returns the corresponding routeConfig object, and an error if there is any.
func (c *FakeRouteConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RouteConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(routeconfigsResource, c.ns, name), &v1alpha1.RouteConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RouteConfig), err
}

// List takes label and field selectors, and returns the list of RouteConfigs that match those selectors.
func (c *FakeRouteConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RouteConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(routeconfigsResource, routeconfigsKind, c.ns, opts), &v1alpha1.RouteConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RouteConfigList{ListMeta: obj.(*v1alpha1.RouteConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.RouteConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested routeConfigs.
func (c *FakeRouteConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(routeconfigsResource, c.ns, opts))

}

// Create takes the representation of a routeConfig and creates it.  Returns the server's representation of the routeConfig, and an error, if there is any.
func (c *FakeRouteConfigs) Create(ctx context.Context, routeConfig *v1alpha1.RouteConfig, opts v1.CreateOptions) (result *v1alpha1.RouteConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(routeconfigsResource, c.ns, routeConfig), &v1alpha1.RouteConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RouteConfig), err
}

// Update takes the representation of a routeConfig and updates it. Returns the server's representation of the routeConfig, and an error, if there is any.
func (c *FakeRouteConfigs) Update(ctx context.Context, routeConfig *v1alpha1.RouteConfig, opts v1.UpdateOptions) (result *v1alpha1.RouteConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(routeconfigsResource, c.ns, routeConfig), &v1alpha1.RouteConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RouteConfig), err
}

// Delete takes name of the routeConfig and deletes it. Returns an error if one occurs.
func (c *FakeRouteConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(routeconfigsResource, c.ns, name), &v1alpha1.RouteConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRouteConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(routeconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RouteConfigList{})
	return err
}

// Patch applies the patch and returns the patched routeConfig.
func (c *FakeRouteConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RouteConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(routeconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RouteConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RouteConfig), err
}
