/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/dmol5e/api-management-app/api-publisher/pkg/apis/apimanagement/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAPIConfigs implements APIConfigInterface
type FakeAPIConfigs struct {
	Fake *FakeApimanagementV1alpha1
	ns   string
}

var apiconfigsResource = schema.GroupVersionResource{Group: "apimanagement.cloud", Version: "v1alpha1", Resource: "apiconfigs"}

var apiconfigsKind = schema.GroupVersionKind{Group: "apimanagement.cloud", Version: "v1alpha1", Kind: "APIConfig"}

// Get takes name of the aPIConfig, and returns the corresponding aPIConfig object, and an error if there is any.
func (c *FakeAPIConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APIConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apiconfigsResource, c.ns, name), &v1alpha1.APIConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIConfig), err
}

// List takes label and field selectors, and returns the list of APIConfigs that match those selectors.
func (c *FakeAPIConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APIConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apiconfigsResource, apiconfigsKind, c.ns, opts), &v1alpha1.APIConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.APIConfigList{ListMeta: obj.(*v1alpha1.APIConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.APIConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aPIConfigs.
func (c *FakeAPIConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apiconfigsResource, c.ns, opts))

}

// Create takes the representation of a aPIConfig and creates it.  Returns the server's representation of the aPIConfig, and an error, if there is any.
func (c *FakeAPIConfigs) Create(ctx context.Context, aPIConfig *v1alpha1.APIConfig, opts v1.CreateOptions) (result *v1alpha1.APIConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apiconfigsResource, c.ns, aPIConfig), &v1alpha1.APIConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIConfig), err
}

// Update takes the representation of a aPIConfig and updates it. Returns the server's representation of the aPIConfig, and an error, if there is any.
func (c *FakeAPIConfigs) Update(ctx context.Context, aPIConfig *v1alpha1.APIConfig, opts v1.UpdateOptions) (result *v1alpha1.APIConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apiconfigsResource, c.ns, aPIConfig), &v1alpha1.APIConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIConfig), err
}

// Delete takes name of the aPIConfig and deletes it. Returns an error if one occurs.
func (c *FakeAPIConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(apiconfigsResource, c.ns, name), &v1alpha1.APIConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAPIConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apiconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.APIConfigList{})
	return err
}

// Patch applies the patch and returns the patched aPIConfig.
func (c *FakeAPIConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apiconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.APIConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIConfig), err
}
